### ISSUE TITLE
[ERROR] apiRequest failed. HTTPError: 304

### ISSUE THREAD

**Issue by alimovz** [realriot/ff4d#19]
I got everything to work on Ubuntu 14 server. 
`./ff4d.py -d -df /mnt/dropbox/ `successfully mounts my dropbox to a local directory. The key is pulled from ff4d.config

However, when I run `df -m` on my server, I get this this output:

unique: 6, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 2501
getattr /
[DEBUG] Called: getattr() - Path: /
[DEBUG] Found cached metadata for: /
[DEBUG] Metadata directory deepcheck: False
[DEBUG] Cache expired for: /
[DEBUG] cachets: 1485731249 - 1485731264
[DEBUG] Checking for changes on the remote endpoint for folder: /
[ERROR] apiRequest failed. HTTPError: 304
[DEBUG] No remote changes detected for folder: / (Traceback (most recent call last):
  File "./ff4d.py", line 169, in getDropboxMetadata
    item = self.dbxMetadata(path, item['hash'])
  File "./ff4d.py", line 52, in dbxMetadata
    result = self.ar.get('https://api.dropbox.com/1/metadata/auto' + path, args)
  File "./ff4d.py", line 533, in get
    raise Exception, 'apiRequest failed. HTTPError: ' + str(e.code)
Exception: apiRequest failed. HTTPError: 304
)
[DEBUG] Returning properties for directory: / ({'st_ctime': 1485731264, 'st_mtime': 1485731264, 'st_nlink': 2, 'st_gid': 0, 'st_size': 0, 'st_atime': 1485731264, 'st_uid': 0, 'st_mode': 16877})
   unique: 6, success, outsize: 120
unique: 7, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 2501
statfs /
   unique: 7, success, outsize: 96

After which, the filesystem becomes read-only and I cannot put any files there.

**Comment by farmisen** [comment]
Probably because of what's mentioned in https://github.com/realriot/ff4d/issues/16

**Comment by realriot** [comment]
Rewritten code. Pls test again.
