### ISSUE TITLE
Broken for some filenames?

### ISSUE THREAD

**Issue by jbreitbart** [realriot/ff4d#4]
I just tried ff4d and it seems to work for some / directories but not for all of them. Here are some of the log messages:

$ ./ff4d.py -ap XXXXX  /dropbox/

---
- FUSE Filesystem 4 Dropbox                            *
-                                                      *
- Copyright 2014                                       *
- Sascha Schmidt sascha@schmidt.ps                   *
-                                                      *
- https://github.com/realriot/ff4d/blob/master/LICENSE *
  ********************************************************

Welcome 
Space used: 
Space available: 

Starting FUSE...
fusermount: failed to open /etc/fuse.conf: Permission denied
[ERROR] apiRequest failed. HTTPError: 404
[ERROR] Could not fetch metadata for: /.Trash (Traceback (most recent call last):
  File "./ff4d.py", line 200, in getDropboxMetadata
    item = self.dbxMetadata(path)
  File "./ff4d.py", line 52, in dbxMetadata
    result = self.ar.get('https://api.dropbox.com/1/metadata/auto' + path, args)
  File "./ff4d.py", line 533, in get
    raise Exception, 'apiRequest failed. HTTPError: ' + str(e.code)
Exception: apiRequest failed. HTTPError: 404
)
[ERROR] apiRequest failed. HTTPError: 404
[ERROR] Could not fetch metadata for: /.Trash-1000 (Traceback (most recent call last):
  File "./ff4d.py", line 200, in getDropboxMetadata
    item = self.dbxMetadata(path)
  File "./ff4d.py", line 52, in dbxMetadata
    result = self.ar.get('https://api.dropbox.com/1/metadata/auto' + path, args)
  File "./ff4d.py", line 533, in get
    raise Exception, 'apiRequest failed. HTTPError: ' + str(e.code)
Exception: apiRequest failed. HTTPError: 404
)
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 404
[ERROR] Could not open remote file: /DeerEditor#1.pdf (Traceback (most recent call last):
  File "./ff4d.py", line 304, in read
    self.openfh[fh]['f'] = self.dbxFilehandle(path, offset)
  File "./ff4d.py", line 99, in dbxFilehandle
    result = self.ar.get('https://api-content.dropbox.com/1/files/auto' + path, None, seekheader, True)
  File "./ff4d.py", line 533, in get
    raise Exception, 'apiRequest failed. HTTPError: ' + str(e.code)
Exception: apiRequest failed. HTTPError: 404
)

Any idea?

**Comment by jbreitbart** [comment]
Thanks for your help, but this did not solve the issue.

$ ./ff4d.py /tmp/a/
********************************************************
* FUSE Filesystem 4 Dropbox                            *
*                                                      *
* Copyright 2014                                       *
* Sascha Schmidt <sascha@schmidt.ps>                   *
*                                                      *
* https://github.com/realriot/ff4d/blob/master/LICENSE *
********************************************************

Welcome 
Space used: 
Space available: 

Starting FUSE...
[ERROR] apiRequest failed. HTTPError: 404
[ERROR] Could not fetch metadata for: /.Trash (Traceback (most recent call last):
  File "./ff4d.py", line 200, in getDropboxMetadata
    item = self.dbxMetadata(path)
  File "./ff4d.py", line 52, in dbxMetadata
    result = self.ar.get('https://api.dropbox.com/1/metadata/auto' + path, args)
  File "./ff4d.py", line 533, in get
    raise Exception, 'apiRequest failed. HTTPError: ' + str(e.code)
Exception: apiRequest failed. HTTPError: 404
)
[ERROR] apiRequest failed. HTTPError: 404
[ERROR] Could not fetch metadata for: /.Trash-1000 (Traceback (most recent call last):
  File "./ff4d.py", line 200, in getDropboxMetadata
    item = self.dbxMetadata(path)
  File "./ff4d.py", line 52, in dbxMetadata
    result = self.ar.get('https://api.dropbox.com/1/metadata/auto' + path, args)
  File "./ff4d.py", line 533, in get
    raise Exception, 'apiRequest failed. HTTPError: ' + str(e.code)
Exception: apiRequest failed. HTTPError: 404
)
[ERROR] apiRequest failed. HTTPError: 404
[ERROR] Could not fetch metadata for: /lager/.hidden (Traceback (most recent call last):
  File "./ff4d.py", line 200, in getDropboxMetadata
    item = self.dbxMetadata(path)
  File "./ff4d.py", line 52, in dbxMetadata
    result = self.ar.get('https://api.dropbox.com/1/metadata/auto' + path, args)
  File "./ff4d.py", line 533, in get
    raise Exception, 'apiRequest failed. HTTPError: ' + str(e.code)
Exception: apiRequest failed. HTTPError: 404
)
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304
[ERROR] apiRequest failed. HTTPError: 304

And ls looks like:

$ ls
ls: cannot access creative community: No such file or directory
ls: cannot access lazy Sunday: No such file or directory
ls: cannot access not stock: No such file or directory
ls: cannot access seattletrip: No such file or directory
ls: cannot access Simplify: No such file or directory
ls: cannot access slow down: No such file or directory
ls: cannot access step out of the expected: No such file or directory
ls: cannot access wired: No such file or directory
ls: cannot access writing prompts: No such file or directory
creative community  lazy Sunday  not stock  seattletrip  Simplify  slow down  step out of the expected  wired  writing prompts

Any other idea how I may fix this issue?

**Comment by realriot** [comment]
Rewritten code. Pls test again.
